title: "FYI Kamran"
url: "https://fyikamran.com"
permalink: /:slug/

plugins:
  - jekyll-sitemap

author: Kamran
description: "Academic Developer with background in Teaching, Engineering, and Indie App Development."