title: "fyiKamran"
url: "https://fyikamran.com"
permalink: /:slug/
theme: null

plugins:
  - jekyll-sitemap

author: Kamran
description: "Kamran is an Academic Developer with a background in teaching, engineering, and indie development."

schema:
  person_id: "https://fyikamran.com/#person"
  name: "Kamran"
  alternate_name: "Muhammad Kamran"
  twitter: "fyikamran"
  image: "https://fyikamran.com/images/kamran-profile.jpg"
  description: "Kamran is an Academic Developer with a background in teaching, engineering, and indie development."
  job_title: "Academic Developer"
  works_for_name: "London South Bank University"
  works_for_url: "https://www.lsbu.ac.uk"
  alumni_nust: "National University of Sciences and Technology (NUST)"
  alumni_nust_url: "https://nust.edu.pk"
  linkedin: "https://www.linkedin.com/in/fyikamran"
  youtube: "https://www.youtube.com/@fyikamran"
  github: "https://github.com/fyikamran"
  medium: "https://medium.com/@fyikamran"
  orcid: "https://orcid.org/0000-0001-8968-4266"
  scholar: "https://scholar.google.com/citations?user=jSnS_QMAAAAJ"
